### ISSUE TITLE
Can we add FbaCatalog to the list?

### ISSUE THREAD

**Issue by skatkov** [dehenne/awesome-visibility#7]
I'm the founder of fbacatalog.com project. Project mainly focuses on Amazon Seller software -- but I'm happy to list anyone in the space (we're mainly listing SaaS now, but we're working on adding different plugins/ extensions and etc). We have a free listing, premium listing and featured listing.

Do you think this will be a good addition to this repo?

**Comment by dehenne** [comment]
Is it possible to sign up or send you a link as Amazon Seller? I think if you still have a way that someone send you a link / product, it should fit. But I couldn't find such a possibility.

How do I understand that you collect the links yourselves? Is that correct? The list here is for services where you can register yourself, introduce yourself or just suggest a Link. Do you know what I mean? :-)

**Comment by skatkov** [comment]
Yeap, I know what you mean. I mostly gather all the links myself, but we have a contact form ( https://fbacatalog.com/contact.html ) -- everyone used that to submit their own projects.

**Comment by dehenne** [comment]
Ah awesome. Than I will add it next week and mention the contact form.

**Comment by dehenne** [comment]
https://github.com/dehenne/awesome-visibility/commit/f1d46bcdaf58d002ff4b521a54119e9199ac8690
